#!/bin/sh

set -e

SENTINEL_CONFIGURATION_FILE=/etc/sentinel.conf

QUORUM=$QUORUM
: ${QUORUM:=2}

GROUP_NAME=$GROUP_NAME
: ${GROUP_NAME:=mymaster}

MASTER_PORT=$MASTER_PORT
: ${MASTER_PORT:=6379}

echo "port 26379" >> $SENTINEL_CONFIGURATION_FILE
echo "sentinel monitor $GROUP_NAME $MASTER_IP $MASTER_PORT $QUORUM" >> $SENTINEL_CONFIGURATION_FILE

redis-server $SENTINEL_CONFIGURATION_FILE --sentinel